"""Add categories, budgets and transaction.category_id

Revision ID: 174f3f65adcc
Revises: 68ee136086e9
Create Date: 2025-11-06 23:35:26.856594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '174f3f65adcc'
down_revision: Union[str, None] = '68ee136086e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_category_id'), 'transactions', ['category_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_category_id'), table_name='transactions')
    op.drop_column('transactions', 'category_id')
    # ### end Alembic commands ###
