"""Add user preferences fields

Revision ID: 68ee136086e9
Revises: db9e90e6fe08
Create Date: 2025-11-06 23:11:06.847290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ee136086e9'
down_revision: Union[str, None] = 'db9e90e6fe08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bad_threshold', sa.Integer(), nullable=True, comment='Valor abaixo indica cenário ruim (vermelho)'))
    op.add_column('users', sa.Column('ok_threshold', sa.Integer(), nullable=True, comment='Valor até este limite indica cenário ok (amarelo)'))
    op.add_column('users', sa.Column('good_threshold', sa.Integer(), nullable=True, comment='Valor acima indica cenário bom (verde)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'good_threshold')
    op.drop_column('users', 'ok_threshold')
    op.drop_column('users', 'bad_threshold')
    # ### end Alembic commands ###
