"""Add user.auto_categorize_enabled flag

Revision ID: 961fd5c80514
Revises: a334d0ce25cd
Create Date: 2025-11-07 00:18:33.387682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '961fd5c80514'
down_revision: Union[str, None] = 'a334d0ce25cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auto_categorize_enabled', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auto_categorize_enabled')
    # ### end Alembic commands ###
